In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('player_info.csv')
df=pd.DataFrame(data)
df

,image,player_name,team,role,batting_style,bowling_style
0,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Rohit Sharma,India,Batsman,Right Handed Bat,Right-arm offbreak
1,https://static.cricbuzz.com/a/img/v1/i1/c59194...,Yashasvi Jaiswal\nBatsman,India,Batsman,Left Handed Bat,Right-arm legbreak
2,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Virat Kohli\nBatsman,India,Batsman,Right Handed Bat,Right-arm medium
3,https://static.cricbuzz.com/a/img/v1/i1/c35248...,Suryakumar Yadav\nBatsman,India,Batsman,Right Handed Bat,Right-arm offbreak
4,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Hardik Pandya\nBatting Allrounder,India,Batting Allrounder,Right Handed Bat,Right-arm fast-medium
...,...,...,...,...,...,...
299,https://static.cricbuzz.com/a/img/v1/i1/c61644...,Haris Rauf\nBowler,Pakistan,Bowler,Right Handed Bat,Right-arm fast
300,https://static.cricbuzz.com/a/img/v1/i1/c58235...,Abbas Afridi\nBowler,Pakistan,Bowler,Right Handed Bat,Right-arm fast-medium
301,https://static.cricbuzz.com/a/img/v1/i1/c17081...,Mohammad Amir\nBowler,Pakistan,Bowler,Left Handed Bat,Left-arm fast-medium
302,https://static.cricbuzz.com/a/img/v1/i1/c61643...,Naseem Shah\nBowler,Pakistan,Bowler,Right Handed Bat,Right-arm fast
303,https://static.cricbuzz.com/a/img/v1/i1/c61644...,Shaheen Afridi\nBowler,Pakistan,Bowler,Left Handed Bat,Left-arm fast-medium

In [3]:
df.insert(
    0,
    "player_id",
    ["P" + str(i) for i in range(1, len(df) + 1)]
)
df

,player_id,image,player_name,team,role,batting_style,bowling_style
0,P1,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Rohit Sharma,India,Batsman,Right Handed Bat,Right-arm offbreak
1,P2,https://static.cricbuzz.com/a/img/v1/i1/c59194...,Yashasvi Jaiswal\nBatsman,India,Batsman,Left Handed Bat,Right-arm legbreak
2,P3,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Virat Kohli\nBatsman,India,Batsman,Right Handed Bat,Right-arm medium
3,P4,https://static.cricbuzz.com/a/img/v1/i1/c35248...,Suryakumar Yadav\nBatsman,India,Batsman,Right Handed Bat,Right-arm offbreak
4,P5,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Hardik Pandya\nBatting Allrounder,India,Batting Allrounder,Right Handed Bat,Right-arm fast-medium
...,...,...,...,...,...,...,...
299,P300,https://static.cricbuzz.com/a/img/v1/i1/c61644...,Haris Rauf\nBowler,Pakistan,Bowler,Right Handed Bat,Right-arm fast
300,P301,https://static.cricbuzz.com/a/img/v1/i1/c58235...,Abbas Afridi\nBowler,Pakistan,Bowler,Right Handed Bat,Right-arm fast-medium
301,P302,https://static.cricbuzz.com/a/img/v1/i1/c17081...,Mohammad Amir\nBowler,Pakistan,Bowler,Left Handed Bat,Left-arm fast-medium
302,P303,https://static.cricbuzz.com/a/img/v1/i1/c61643...,Naseem Shah\nBowler,Pakistan,Bowler,Right Handed Bat,Right-arm fast
303,P304,https://static.cricbuzz.com/a/img/v1/i1/c61644...,Shaheen Afridi\nBowler,Pakistan,Bowler,Left Handed Bat,Left-arm fast-medium

In [4]:
role_map = {
    "batsman": "bat",
    "bowler": "bowl",
    "batting allrounder": "ar",
    "bowling allrounder": "ar",
    "allrounder": "ar",
    "wicketkeeper": "wk",
    "wicket-keeper": "wk",
    "WK-Batsman": "wk",
    "wk batsman": "wk"
}

df["role_clean"] = (
    df["role"]
    .str.lower()
    .str.replace(r"[-_]", " ", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .map(role_map)
)
df.head(10)

,player_id,image,player_name,team,role,batting_style,bowling_style,role_clean
0,P1,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Rohit Sharma,India,Batsman,Right Handed Bat,Right-arm offbreak,bat
1,P2,https://static.cricbuzz.com/a/img/v1/i1/c59194...,Yashasvi Jaiswal\nBatsman,India,Batsman,Left Handed Bat,Right-arm legbreak,bat
2,P3,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Virat Kohli\nBatsman,India,Batsman,Right Handed Bat,Right-arm medium,bat
3,P4,https://static.cricbuzz.com/a/img/v1/i1/c35248...,Suryakumar Yadav\nBatsman,India,Batsman,Right Handed Bat,Right-arm offbreak,bat
4,P5,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Hardik Pandya\nBatting Allrounder,India,Batting Allrounder,Right Handed Bat,Right-arm fast-medium,ar
5,P6,https://static.cricbuzz.com/a/img/v1/i1/c59380...,Shivam Dube\nBatting Allrounder,India,Batting Allrounder,Left Handed Bat,Right-arm medium,ar
6,P7,https://static.cricbuzz.com/a/img/v1/i1/c61652...,Ravindra Jadeja\nBowling Allrounder,India,Bowling Allrounder,Left Handed Bat,Left-arm orthodox,ar
7,P8,https://static.cricbuzz.com/a/img/v1/i1/c61652...,Axar Patel\nBowling Allrounder,India,Bowling Allrounder,Left Handed Bat,Left-arm orthodox,ar
8,P9,https://static.cricbuzz.com/a/img/v1/i1/c61652...,Rishabh Pant\nWK-Batsman,India,WK-Batsman,Left Handed Bat,NaN,wk
9,P10,https://static.cricbuzz.com/a/img/v1/i1/c22628...,Sanju Samson\nWK-Batsman,India,WK-Batsman,Right Handed Bat,NaN,wk

In [5]:
df["player_name"] = (
    df["player_name"]
    .str.replace(r"\s*(Batsman|Bowler|Batting Allrounder|Bowling Allrounder|Allrounder|Wicketkeeper).*",
                 "",
                 regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

df[df.duplicated(subset=["player_name", "team"], keep=False)]
df

,player_id,image,player_name,team,role,batting_style,bowling_style,role_clean
0,P1,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Rohit Sharma,India,Batsman,Right Handed Bat,Right-arm offbreak,bat
1,P2,https://static.cricbuzz.com/a/img/v1/i1/c59194...,Yashasvi Jaiswal,India,Batsman,Left Handed Bat,Right-arm legbreak,bat
2,P3,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Virat Kohli,India,Batsman,Right Handed Bat,Right-arm medium,bat
3,P4,https://static.cricbuzz.com/a/img/v1/i1/c35248...,Suryakumar Yadav,India,Batsman,Right Handed Bat,Right-arm offbreak,bat
4,P5,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Hardik Pandya,India,Batting Allrounder,Right Handed Bat,Right-arm fast-medium,ar
...,...,...,...,...,...,...,...,...
299,P300,https://static.cricbuzz.com/a/img/v1/i1/c61644...,Haris Rauf,Pakistan,Bowler,Right Handed Bat,Right-arm fast,bowl
300,P301,https://static.cricbuzz.com/a/img/v1/i1/c58235...,Abbas Afridi,Pakistan,Bowler,Right Handed Bat,Right-arm fast-medium,bowl
301,P302,https://static.cricbuzz.com/a/img/v1/i1/c17081...,Mohammad Amir,Pakistan,Bowler,Left Handed Bat,Left-arm fast-medium,bowl
302,P303,https://static.cricbuzz.com/a/img/v1/i1/c61643...,Naseem Shah,Pakistan,Bowler,Right Handed Bat,Right-arm fast,bowl
303,P304,https://static.cricbuzz.com/a/img/v1/i1/c61644...,Shaheen Afridi,Pakistan,Bowler,Left Handed Bat,Left-arm fast-medium,bowl

In [6]:
df["team"] = (
    df["team"]
    .str.strip()
    .str.title()
)
df

,player_id,image,player_name,team,role,batting_style,bowling_style,role_clean
0,P1,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Rohit Sharma,India,Batsman,Right Handed Bat,Right-arm offbreak,bat
1,P2,https://static.cricbuzz.com/a/img/v1/i1/c59194...,Yashasvi Jaiswal,India,Batsman,Left Handed Bat,Right-arm legbreak,bat
2,P3,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Virat Kohli,India,Batsman,Right Handed Bat,Right-arm medium,bat
3,P4,https://static.cricbuzz.com/a/img/v1/i1/c35248...,Suryakumar Yadav,India,Batsman,Right Handed Bat,Right-arm offbreak,bat
4,P5,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Hardik Pandya,India,Batting Allrounder,Right Handed Bat,Right-arm fast-medium,ar
...,...,...,...,...,...,...,...,...
299,P300,https://static.cricbuzz.com/a/img/v1/i1/c61644...,Haris Rauf,Pakistan,Bowler,Right Handed Bat,Right-arm fast,bowl
300,P301,https://static.cricbuzz.com/a/img/v1/i1/c58235...,Abbas Afridi,Pakistan,Bowler,Right Handed Bat,Right-arm fast-medium,bowl
301,P302,https://static.cricbuzz.com/a/img/v1/i1/c17081...,Mohammad Amir,Pakistan,Bowler,Left Handed Bat,Left-arm fast-medium,bowl
302,P303,https://static.cricbuzz.com/a/img/v1/i1/c61643...,Naseem Shah,Pakistan,Bowler,Right Handed Bat,Right-arm fast,bowl
303,P304,https://static.cricbuzz.com/a/img/v1/i1/c61644...,Shaheen Afridi,Pakistan,Bowler,Left Handed Bat,Left-arm fast-medium,bowl

In [7]:
bat_map = {
    "right handed bat": "RHB",
    "left handed bat": "LHB"
}

df["batting_style_clean"] = (
    df["batting_style"]
    .str.lower()
    .str.strip()
    .map(bat_map)
)
df

,player_id,image,player_name,team,role,batting_style,bowling_style,role_clean,batting_style_clean
0,P1,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Rohit Sharma,India,Batsman,Right Handed Bat,Right-arm offbreak,bat,RHB
1,P2,https://static.cricbuzz.com/a/img/v1/i1/c59194...,Yashasvi Jaiswal,India,Batsman,Left Handed Bat,Right-arm legbreak,bat,LHB
2,P3,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Virat Kohli,India,Batsman,Right Handed Bat,Right-arm medium,bat,RHB
3,P4,https://static.cricbuzz.com/a/img/v1/i1/c35248...,Suryakumar Yadav,India,Batsman,Right Handed Bat,Right-arm offbreak,bat,RHB
4,P5,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Hardik Pandya,India,Batting Allrounder,Right Handed Bat,Right-arm fast-medium,ar,RHB
...,...,...,...,...,...,...,...,...,...
299,P300,https://static.cricbuzz.com/a/img/v1/i1/c61644...,Haris Rauf,Pakistan,Bowler,Right Handed Bat,Right-arm fast,bowl,RHB
300,P301,https://static.cricbuzz.com/a/img/v1/i1/c58235...,Abbas Afridi,Pakistan,Bowler,Right Handed Bat,Right-arm fast-medium,bowl,RHB
301,P302,https://static.cricbuzz.com/a/img/v1/i1/c17081...,Mohammad Amir,Pakistan,Bowler,Left Handed Bat,Left-arm fast-medium,bowl,LHB
302,P303,https://static.cricbuzz.com/a/img/v1/i1/c61643...,Naseem Shah,Pakistan,Bowler,Right Handed Bat,Right-arm fast,bowl,RHB
303,P304,https://static.cricbuzz.com/a/img/v1/i1/c61644...,Shaheen Afridi,Pakistan,Bowler,Left Handed Bat,Left-arm fast-medium,bowl,LHB

In [8]:
df["bowling_arm"] = df["bowling_style"].str.extract(r"(Right|Left)-arm", expand=False)
df["bowling_type"] = df["bowling_style"].str.extract(
    r"(fast-medium|fast|medium|offbreak|legbreak|orthodox)",
    expand=False
)
df

,player_id,image,player_name,team,role,batting_style,bowling_style,role_clean,batting_style_clean,bowling_arm,bowling_type
0,P1,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Rohit Sharma,India,Batsman,Right Handed Bat,Right-arm offbreak,bat,RHB,Right,offbreak
1,P2,https://static.cricbuzz.com/a/img/v1/i1/c59194...,Yashasvi Jaiswal,India,Batsman,Left Handed Bat,Right-arm legbreak,bat,LHB,Right,legbreak
2,P3,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Virat Kohli,India,Batsman,Right Handed Bat,Right-arm medium,bat,RHB,Right,medium
3,P4,https://static.cricbuzz.com/a/img/v1/i1/c35248...,Suryakumar Yadav,India,Batsman,Right Handed Bat,Right-arm offbreak,bat,RHB,Right,offbreak
4,P5,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Hardik Pandya,India,Batting Allrounder,Right Handed Bat,Right-arm fast-medium,ar,RHB,Right,fast-medium
...,...,...,...,...,...,...,...,...,...,...,...
299,P300,https://static.cricbuzz.com/a/img/v1/i1/c61644...,Haris Rauf,Pakistan,Bowler,Right Handed Bat,Right-arm fast,bowl,RHB,Right,fast
300,P301,https://static.cricbuzz.com/a/img/v1/i1/c58235...,Abbas Afridi,Pakistan,Bowler,Right Handed Bat,Right-arm fast-medium,bowl,RHB,Right,fast-medium
301,P302,https://static.cricbuzz.com/a/img/v1/i1/c17081...,Mohammad Amir,Pakistan,Bowler,Left Handed Bat,Left-arm fast-medium,bowl,LHB,Left,fast-medium
302,P303,https://static.cricbuzz.com/a/img/v1/i1/c61643...,Naseem Shah,Pakistan,Bowler,Right Handed Bat,Right-arm fast,bowl,RHB,Right,fast
303,P304,https://static.cricbuzz.com/a/img/v1/i1/c61644...,Shaheen Afridi,Pakistan,Bowler,Left Handed Bat,Left-arm fast-medium,bowl,LHB,Left,fast-medium

In [10]:
# df["player_name_clean"] = clean_name(df["player_name"])
# df["player_name_clean"] = (
#     df["player_name_clean"]
#     .str.replace(r"\s*wk-\s*$", "", regex=True)
#     .str.strip()
# )
# df.head(10)

NameError: name 'clean_name' is not defined

In [ ]:
df.to_csv('player_info_clean.csv',index=False)

In [12]:
# import pandas as pd
# data1=pd.read_csv('batting_summary.csv')
# dfb=pd.DataFrame(data1)
# dfb

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,CANADA vs UNITED STATES OF AMERICA,CANADA,1,Aaron Johnson,c NR Kumar b Harmeet Singh,23,16,5,0,143.75
1,CANADA vs UNITED STATES OF AMERICA,CANADA,2,Navneet Dhaliwal,c Jessy Singh b CJ Anderson,61,44,6,3,138.64
2,CANADA vs UNITED STATES OF AMERICA,CANADA,3,Pargat Singh,run out (Jessy Singh/Monank Patel),5,7,0,0,71.43
3,CANADA vs UNITED STATES OF AMERICA,CANADA,4,Nicholas Kirton,c CJ Anderson b Ali Khan,51,31,3,2,164.52
4,CANADA vs UNITED STATES OF AMERICA,CANADA,5,Shreyas Movva (wk),not out,32,16,2,2,200.00
...,...,...,...,...,...,...,...,...,...,...
847,INDIA vs SOUTH AFRICA,SOUTH AFRICA,6,David Miller,c Suryakumar Yadav b Hardik Pandya,21,17,1,1,123.53
848,INDIA vs SOUTH AFRICA,SOUTH AFRICA,7,Marco Jansen,b Bumrah,2,4,0,0,50.00
849,INDIA vs SOUTH AFRICA,SOUTH AFRICA,8,Keshav Maharaj,not out,2,7,0,0,28.57
850,INDIA vs SOUTH AFRICA,SOUTH AFRICA,9,Kagiso Rabada,c Suryakumar Yadav b Hardik Pandya,4,3,1,0,133.33
851,INDIA vs SOUTH AFRICA,SOUTH AFRICA,10,Anrich Nortje,not out,1,1,0,0,100.00

In [13]:
# dfb = pd.read_csv("batting_summary.csv")

# dfb = dfb.rename(columns={
#     "match": "match_name",
#     "teamInnings": "team",
#     "battingPos": "batting_pos",
#     "batsmanName": "player_name",
#     "dismissal": "dismissal",
#     "runs": "runs",
#     "balls": "balls",
#     "4s": "fours",
#     "6s": "sixes",
#     "SR": "strike_rate"
# })
# dfb

,match_name,team,batting_pos,player_name,dismissal,runs,balls,fours,sixes,strike_rate
0,CANADA vs UNITED STATES OF AMERICA,CANADA,1,Aaron Johnson,c NR Kumar b Harmeet Singh,23,16,5,0,143.75
1,CANADA vs UNITED STATES OF AMERICA,CANADA,2,Navneet Dhaliwal,c Jessy Singh b CJ Anderson,61,44,6,3,138.64
2,CANADA vs UNITED STATES OF AMERICA,CANADA,3,Pargat Singh,run out (Jessy Singh/Monank Patel),5,7,0,0,71.43
3,CANADA vs UNITED STATES OF AMERICA,CANADA,4,Nicholas Kirton,c CJ Anderson b Ali Khan,51,31,3,2,164.52
4,CANADA vs UNITED STATES OF AMERICA,CANADA,5,Shreyas Movva (wk),not out,32,16,2,2,200.00
...,...,...,...,...,...,...,...,...,...,...
847,INDIA vs SOUTH AFRICA,SOUTH AFRICA,6,David Miller,c Suryakumar Yadav b Hardik Pandya,21,17,1,1,123.53
848,INDIA vs SOUTH AFRICA,SOUTH AFRICA,7,Marco Jansen,b Bumrah,2,4,0,0,50.00
849,INDIA vs SOUTH AFRICA,SOUTH AFRICA,8,Keshav Maharaj,not out,2,7,0,0,28.57
850,INDIA vs SOUTH AFRICA,SOUTH AFRICA,9,Kagiso Rabada,c Suryakumar Yadav b Hardik Pandya,4,3,1,0,133.33
851,INDIA vs SOUTH AFRICA,SOUTH AFRICA,10,Anrich Nortje,not out,1,1,0,0,100.00

In [14]:
# dfb["player_name"] = (
#     dfb["player_name"]
#     .str.replace(r"\(wk\)", "", regex=True)
#     .str.replace(r"\s+", " ", regex=True)
#     .str.strip()
# )
# dfb

,match_name,team,batting_pos,player_name,dismissal,runs,balls,fours,sixes,strike_rate
0,CANADA vs UNITED STATES OF AMERICA,CANADA,1,Aaron Johnson,c NR Kumar b Harmeet Singh,23,16,5,0,143.75
1,CANADA vs UNITED STATES OF AMERICA,CANADA,2,Navneet Dhaliwal,c Jessy Singh b CJ Anderson,61,44,6,3,138.64
2,CANADA vs UNITED STATES OF AMERICA,CANADA,3,Pargat Singh,run out (Jessy Singh/Monank Patel),5,7,0,0,71.43
3,CANADA vs UNITED STATES OF AMERICA,CANADA,4,Nicholas Kirton,c CJ Anderson b Ali Khan,51,31,3,2,164.52
4,CANADA vs UNITED STATES OF AMERICA,CANADA,5,Shreyas Movva,not out,32,16,2,2,200.00
...,...,...,...,...,...,...,...,...,...,...
847,INDIA vs SOUTH AFRICA,SOUTH AFRICA,6,David Miller,c Suryakumar Yadav b Hardik Pandya,21,17,1,1,123.53
848,INDIA vs SOUTH AFRICA,SOUTH AFRICA,7,Marco Jansen,b Bumrah,2,4,0,0,50.00
849,INDIA vs SOUTH AFRICA,SOUTH AFRICA,8,Keshav Maharaj,not out,2,7,0,0,28.57
850,INDIA vs SOUTH AFRICA,SOUTH AFRICA,9,Kagiso Rabada,c Suryakumar Yadav b Hardik Pandya,4,3,1,0,133.33
851,INDIA vs SOUTH AFRICA,SOUTH AFRICA,10,Anrich Nortje,not out,1,1,0,0,100.00

In [15]:
dfb["team"] = dfb["team"].str.strip().str.title()
dfb

,match_name,team,batting_pos,player_name,dismissal,runs,balls,fours,sixes,strike_rate
0,CANADA vs UNITED STATES OF AMERICA,Canada,1,Aaron Johnson,c NR Kumar b Harmeet Singh,23,16,5,0,143.75
1,CANADA vs UNITED STATES OF AMERICA,Canada,2,Navneet Dhaliwal,c Jessy Singh b CJ Anderson,61,44,6,3,138.64
2,CANADA vs UNITED STATES OF AMERICA,Canada,3,Pargat Singh,run out (Jessy Singh/Monank Patel),5,7,0,0,71.43
3,CANADA vs UNITED STATES OF AMERICA,Canada,4,Nicholas Kirton,c CJ Anderson b Ali Khan,51,31,3,2,164.52
4,CANADA vs UNITED STATES OF AMERICA,Canada,5,Shreyas Movva,not out,32,16,2,2,200.00
...,...,...,...,...,...,...,...,...,...,...
847,INDIA vs SOUTH AFRICA,South Africa,6,David Miller,c Suryakumar Yadav b Hardik Pandya,21,17,1,1,123.53
848,INDIA vs SOUTH AFRICA,South Africa,7,Marco Jansen,b Bumrah,2,4,0,0,50.00
849,INDIA vs SOUTH AFRICA,South Africa,8,Keshav Maharaj,not out,2,7,0,0,28.57
850,INDIA vs SOUTH AFRICA,South Africa,9,Kagiso Rabada,c Suryakumar Yadav b Hardik Pandya,4,3,1,0,133.33
851,INDIA vs SOUTH AFRICA,South Africa,10,Anrich Nortje,not out,1,1,0,0,100.00

In [16]:
# num_cols = ["runs", "balls", "fours", "sixes", "strike_rate"]
# dfb[num_cols] = dfb[num_cols].apply(pd.to_numeric, errors="coerce")
# dfb

,match_name,team,batting_pos,player_name,dismissal,runs,balls,fours,sixes,strike_rate
0,CANADA vs UNITED STATES OF AMERICA,Canada,1,Aaron Johnson,c NR Kumar b Harmeet Singh,23,16,5,0,143.75
1,CANADA vs UNITED STATES OF AMERICA,Canada,2,Navneet Dhaliwal,c Jessy Singh b CJ Anderson,61,44,6,3,138.64
2,CANADA vs UNITED STATES OF AMERICA,Canada,3,Pargat Singh,run out (Jessy Singh/Monank Patel),5,7,0,0,71.43
3,CANADA vs UNITED STATES OF AMERICA,Canada,4,Nicholas Kirton,c CJ Anderson b Ali Khan,51,31,3,2,164.52
4,CANADA vs UNITED STATES OF AMERICA,Canada,5,Shreyas Movva,not out,32,16,2,2,200.00
...,...,...,...,...,...,...,...,...,...,...
847,INDIA vs SOUTH AFRICA,South Africa,6,David Miller,c Suryakumar Yadav b Hardik Pandya,21,17,1,1,123.53
848,INDIA vs SOUTH AFRICA,South Africa,7,Marco Jansen,b Bumrah,2,4,0,0,50.00
849,INDIA vs SOUTH AFRICA,South Africa,8,Keshav Maharaj,not out,2,7,0,0,28.57
850,INDIA vs SOUTH AFRICA,South Africa,9,Kagiso Rabada,c Suryakumar Yadav b Hardik Pandya,4,3,1,0,133.33
851,INDIA vs SOUTH AFRICA,South Africa,10,Anrich Nortje,not out,1,1,0,0,100.00

In [17]:
dfb[num_cols].isna().sum()

runs           0
balls          0
fours          0
sixes          0
strike_rate    0
dtype: int64

In [30]:
# def clean_name(s):
#     return (
#         s.str.lower()
#          .str.replace(r"\(c\s*&\s*wk\)|\(wk\)|\(c\)", "", regex=True)
#          .str.replace(r"\s*wk-\s*$", "", regex=True)
#          .str.replace(r"\s+", " ", regex=True)
#          .str.strip()
#     )

# df["player_name_clean"] = clean_name(df["player_name"])


# df["player_name_clean"] = (
#     df["player_name"]
#     .str.lower()
#     .str.replace(r"\s+", " ", regex=True)
#     .str.replace(r"\s*wk-\s*$", "", regex=True)
#     .str.strip()
# )
# df["last_name"] = df["player_name_clean"].str.split().str[-1]

# df.head(20)

,player_id,image,player_name,team,role,batting_style,bowling_style,role_clean,batting_style_clean,bowling_arm,bowling_type,player_name_clean,last_name,team_clean
0,P1,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Rohit Sharma,India,Batsman,Right Handed Bat,Right-arm offbreak,bat,RHB,Right,offbreak,rohit sharma,sharma,india
1,P2,https://static.cricbuzz.com/a/img/v1/i1/c59194...,Yashasvi Jaiswal,India,Batsman,Left Handed Bat,Right-arm legbreak,bat,LHB,Right,legbreak,yashasvi jaiswal,jaiswal,india
2,P3,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Virat Kohli,India,Batsman,Right Handed Bat,Right-arm medium,bat,RHB,Right,medium,virat kohli,kohli,india
3,P4,https://static.cricbuzz.com/a/img/v1/i1/c35248...,Suryakumar Yadav,India,Batsman,Right Handed Bat,Right-arm offbreak,bat,RHB,Right,offbreak,suryakumar yadav,yadav,india
4,P5,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Hardik Pandya,India,Batting Allrounder,Right Handed Bat,Right-arm fast-medium,ar,RHB,Right,fast-medium,hardik pandya,pandya,india
5,P6,https://static.cricbuzz.com/a/img/v1/i1/c59380...,Shivam Dube,India,Batting Allrounder,Left Handed Bat,Right-arm medium,ar,LHB,Right,medium,shivam dube,dube,india
6,P7,https://static.cricbuzz.com/a/img/v1/i1/c61652...,Ravindra Jadeja,India,Bowling Allrounder,Left Handed Bat,Left-arm orthodox,ar,LHB,Left,orthodox,ravindra jadeja,jadeja,india
7,P8,https://static.cricbuzz.com/a/img/v1/i1/c61652...,Axar Patel,India,Bowling Allrounder,Left Handed Bat,Left-arm orthodox,ar,LHB,Left,orthodox,axar patel,patel,india
8,P9,https://static.cricbuzz.com/a/img/v1/i1/c61652...,Rishabh Pant WK-,India,WK-Batsman,Left Handed Bat,NaN,wk,LHB,NaN,NaN,rishabh pant,pant,india
9,P10,https://static.cricbuzz.com/a/img/v1/i1/c22628...,Sanju Samson WK-,India,WK-Batsman,Right Handed Bat,NaN,wk,RHB,NaN,NaN,sanju samson,samson,india
10,P11,https://static.cricbuzz.com/a/img/v1/i1/c61652...,Kuldeep Yadav,India,Bowler,Left Handed Bat,Left-arm wrist-spin,bowl,LHB,Left,NaN,kuldeep yadav,yadav,india
11,P12,https://static.cricbuzz.com/a/img/v1/i1/c24498...,Yuzvendra Chahal,India,Bowler,Right Handed Bat,Right-arm legbreak,bowl,RHB,Right,legbreak,yuzvendra chahal,chahal,india
12,P13,https://static.cricbuzz.com/a/img/v1/i1/c61652...,Arshdeep Singh,India,Bowler,Left Handed Bat,Left-arm fast-medium,bowl,LHB,Left,fast-medium,arshdeep singh,singh,india
13,P14,https://static.cricbuzz.com/a/img/v1/i1/c59194...,Jasprit Bumrah,India,Bowler,Right Handed Bat,Right-arm fast,bowl,RHB,Right,fast,jasprit bumrah,bumrah,india
14,P15,https://static.cricbuzz.com/a/img/v1/i1/c59195...,Mohammed Siraj,India,Bowler,Right Handed Bat,Right-arm fast,bowl,RHB,Right,fast,mohammed siraj,siraj,india
15,P16,https://static.cricbuzz.com/a/img/v1/i1/c18202...,Ross Adair,Ireland,Batsman,Right Handed Bat,Left-arm orthodox,bat,RHB,Left,orthodox,ross adair,adair,ireland
16,P17,https://static.cricbuzz.com/a/img/v1/i1/c24461...,Andrew Balbirnie,Ireland,Batsman,Right Handed Bat,Right-arm offbreak,bat,RHB,Right,offbreak,andrew balbirnie,balbirnie,ireland
17,P18,https://static.cricbuzz.com/a/img/v1/i1/c24464...,Harry Tector,Ireland,Batsman,Right Handed Bat,Right-arm offbreak,bat,RHB,Right,offbreak,harry tector,tector,ireland
18,P19,https://static.cricbuzz.com/a/img/v1/i1/c24465...,Paul Stirling,Ireland,Batting Allrounder,Right Handed Bat,Right-arm offbreak,ar,RHB,Right,offbreak,paul stirling,stirling,ireland
19,P20,https://static.cricbuzz.com/a/img/v1/i1/c24462...,Gareth Delany,Ireland,Batting Allrounder,Right Handed Bat,Right-arm legbreak,ar,RHB,Right,legbreak,gareth delany,delany,ireland

In [31]:


# def resolve_name(row, player_df):
#     name = row["player_name_clean"]
#     team = row["team_clean"]

#     if pd.isna(name) or name == "":
#         return name

#     # 1️⃣ exact match
#     exact = player_df[
#         (player_df["player_name_clean"] == name) &
#         (player_df["team_clean"] == team)
#     ]
#     if len(exact) == 1:
#         return exact.iloc[0]["player_name_clean"]

#     parts = name.split()

#     # 2️⃣ last-name match
#     last = parts[-1]
#     last_matches = player_df[
#         (player_df["last_name"] == last) &
#         (player_df["team_clean"] == team)
#     ]
#     if len(last_matches) == 1:
#         return last_matches.iloc[0]["player_name_clean"]

#     # 3️⃣ first-name match (ONLY if unique in team)
#     first = parts[0]
#     first_matches = player_df[
#         (player_df["player_name_clean"].str.startswith(first + " ")) &
#         (player_df["team_clean"] == team)
#     ]
#     if len(first_matches) == 1:
#         return first_matches.iloc[0]["player_name_clean"]

#     return name



# dfb["player_name_clean"] = dfb.apply(
#     lambda r: resolve_name(r, df),
#     axis=1
# )


# dfb.tail(20)

,match_name,team,batting_pos,player_name,dismissal,runs,balls,fours,sixes,strike_rate,player_name_clean,team_clean,player_id
832,INDIA vs ENGLAND,England,10,Adil Rashid,run out (Suryakumar Yadav),2,2,0,0,100.00,adil rashid,england,P43
833,INDIA vs ENGLAND,England,11,Reece Topley,not out,3,3,0,0,100.00,reece topley,england,P44
834,INDIA vs SOUTH AFRICA,India,1,Rohit (c),c Klaasen b Maharaj,9,5,2,0,180.00,rohit sharma,india,P1
835,INDIA vs SOUTH AFRICA,India,2,Kohli,c Rabada b Marco Jansen,76,59,6,2,128.81,virat kohli,india,P3
836,INDIA vs SOUTH AFRICA,India,3,Pant,c de Kock b Maharaj,0,2,0,0,0.00,rishabh pant,india,NaN
837,INDIA vs SOUTH AFRICA,India,4,Suryakumar Yadav,c Klaasen b Rabada,3,4,0,0,75.00,suryakumar yadav,india,P4
838,INDIA vs SOUTH AFRICA,India,5,Axar,run out (de Kock),47,31,1,4,151.61,axar patel,india,P8
839,INDIA vs SOUTH AFRICA,India,6,Shivam Dube,c David Miller b Nortje,27,16,3,1,168.75,shivam dube,india,P6
840,INDIA vs SOUTH AFRICA,India,7,Hardik Pandya,not out,5,2,1,0,250.00,hardik pandya,india,P5
841,INDIA vs SOUTH AFRICA,India,8,Ravindra Jadeja,c Maharaj b Nortje,2,2,0,0,100.00,ravindra jadeja,india,P7
842,INDIA vs SOUTH AFRICA,South Africa,1,Reeza Hendricks,b Bumrah,4,5,1,0,80.00,reeza hendricks,south africa,P122
843,INDIA vs SOUTH AFRICA,South Africa,2,Quinton de Kock,c Kuldeep Yadav b Arshdeep Singh,39,31,4,1,125.81,quinton de kock,south africa,P125
844,INDIA vs SOUTH AFRICA,South Africa,3,Aiden Markram (c),c Pant b Arshdeep Singh,4,5,1,0,80.00,aiden markram,south africa,P121
845,INDIA vs SOUTH AFRICA,South Africa,4,Tristan Stubbs,b Axar,31,21,3,1,147.62,tristan stubbs,south africa,P128
846,INDIA vs SOUTH AFRICA,South Africa,5,Heinrich Klaasen,c Pant b Hardik Pandya,52,27,2,5,192.59,heinrich klaasen,south africa,P126
847,INDIA vs SOUTH AFRICA,South Africa,6,David Miller,c Suryakumar Yadav b Hardik Pandya,21,17,1,1,123.53,david miller,south africa,P123
848,INDIA vs SOUTH AFRICA,South Africa,7,Marco Jansen,b Bumrah,2,4,0,0,50.00,marco jansen,south africa,P124
849,INDIA vs SOUTH AFRICA,South Africa,8,Keshav Maharaj,not out,2,7,0,0,28.57,keshav maharaj,south africa,P132
850,INDIA vs SOUTH AFRICA,South Africa,9,Kagiso Rabada,c Suryakumar Yadav b Hardik Pandya,4,3,1,0,133.33,kagiso rabada,south africa,P134
851,INDIA vs SOUTH AFRICA,South Africa,10,Anrich Nortje,not out,1,1,0,0,100.00,anrich nortje,south africa,P133

In [32]:
# team_map = {
#     "india": "IND",
#     "england": "ENG",
#     "ireland": "IRE",
#     "canada": "CAN",
#     "united states": "USA",
#     "united state": "USA",
#     "united states of america": "USA",
#     "usa": "USA",
#     "australia": "AUS",
#     "scotland": "SCO",
#     "oman": "OMN",
#     "south africa": "RSA",
#     "sri lanka": "SL",
#     "new zealand": "NZ",
#     "afghanistan": "AFG",
#     "nepal": "NEP",
#     "west indies": "WI",
#     "uganda": "UGA",
#     "papua new guinea": "PNG",
#     "namibia": "NAM",
#     "netherlands": "NED",
#     "bangladesh": "BAN",
#     "pakistan": "PAK"
# }

In [37]:
# def normalize_team(s):
#     return (
#         s.str.lower()
#          .str.replace(r"\s+", " ", regex=True)
#          .str.strip()
#          .map(team_map)
#     )

# dfb["team_clean"] = normalize_team(dfb["team"])
# df["team_clean"]  = normalize_team(df["team"])
# df.head()

,player_id,image,player_name,team,role,batting_style,bowling_style,role_clean,batting_style_clean,bowling_arm,bowling_type,player_name_clean,last_name,team_clean
0,P1,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Rohit Sharma,India,Batsman,Right Handed Bat,Right-arm offbreak,bat,RHB,Right,offbreak,rohit sharma,sharma,IND
1,P2,https://static.cricbuzz.com/a/img/v1/i1/c59194...,Yashasvi Jaiswal,India,Batsman,Left Handed Bat,Right-arm legbreak,bat,LHB,Right,legbreak,yashasvi jaiswal,jaiswal,IND
2,P3,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Virat Kohli,India,Batsman,Right Handed Bat,Right-arm medium,bat,RHB,Right,medium,virat kohli,kohli,IND
3,P4,https://static.cricbuzz.com/a/img/v1/i1/c35248...,Suryakumar Yadav,India,Batsman,Right Handed Bat,Right-arm offbreak,bat,RHB,Right,offbreak,suryakumar yadav,yadav,IND
4,P5,https://static.cricbuzz.com/a/img/v1/i1/c61651...,Hardik Pandya,India,Batting Allrounder,Right Handed Bat,Right-arm fast-medium,ar,RHB,Right,fast-medium,hardik pandya,pandya,IND

In [24]:
# dfb = dfb.drop(columns=[
#     col for col in dfb.columns
#     if col.startswith("player_id")
# ], errors="ignore")

In [39]:
# dfb = dfb.drop(columns=[c for c in dfb.columns if c.startswith("player_id")], errors="ignore")

# dfb = dfb.merge(
#     df[["player_id", "player_name_clean", "team_clean"]],
#     on=["player_name_clean", "team_clean"],
#     how="left"
# )
# dfb.tail(20)

,match_name,team,batting_pos,player_name,dismissal,runs,balls,fours,sixes,strike_rate,player_name_clean,team_clean,player_id
832,INDIA vs ENGLAND,England,10,Adil Rashid,run out (Suryakumar Yadav),2,2,0,0,100.00,adil rashid,ENG,P43
833,INDIA vs ENGLAND,England,11,Reece Topley,not out,3,3,0,0,100.00,reece topley,ENG,P44
834,INDIA vs SOUTH AFRICA,India,1,Rohit (c),c Klaasen b Maharaj,9,5,2,0,180.00,rohit sharma,IND,P1
835,INDIA vs SOUTH AFRICA,India,2,Kohli,c Rabada b Marco Jansen,76,59,6,2,128.81,virat kohli,IND,P3
836,INDIA vs SOUTH AFRICA,India,3,Pant,c de Kock b Maharaj,0,2,0,0,0.00,rishabh pant,IND,P9
837,INDIA vs SOUTH AFRICA,India,4,Suryakumar Yadav,c Klaasen b Rabada,3,4,0,0,75.00,suryakumar yadav,IND,P4
838,INDIA vs SOUTH AFRICA,India,5,Axar,run out (de Kock),47,31,1,4,151.61,axar patel,IND,P8
839,INDIA vs SOUTH AFRICA,India,6,Shivam Dube,c David Miller b Nortje,27,16,3,1,168.75,shivam dube,IND,P6
840,INDIA vs SOUTH AFRICA,India,7,Hardik Pandya,not out,5,2,1,0,250.00,hardik pandya,IND,P5
841,INDIA vs SOUTH AFRICA,India,8,Ravindra Jadeja,c Maharaj b Nortje,2,2,0,0,100.00,ravindra jadeja,IND,P7
842,INDIA vs SOUTH AFRICA,South Africa,1,Reeza Hendricks,b Bumrah,4,5,1,0,80.00,reeza hendricks,RSA,P122
843,INDIA vs SOUTH AFRICA,South Africa,2,Quinton de Kock,c Kuldeep Yadav b Arshdeep Singh,39,31,4,1,125.81,quinton de kock,RSA,P125
844,INDIA vs SOUTH AFRICA,South Africa,3,Aiden Markram (c),c Pant b Arshdeep Singh,4,5,1,0,80.00,aiden markram,RSA,P121
845,INDIA vs SOUTH AFRICA,South Africa,4,Tristan Stubbs,b Axar,31,21,3,1,147.62,tristan stubbs,RSA,P128
846,INDIA vs SOUTH AFRICA,South Africa,5,Heinrich Klaasen,c Pant b Hardik Pandya,52,27,2,5,192.59,heinrich klaasen,RSA,P126
847,INDIA vs SOUTH AFRICA,South Africa,6,David Miller,c Suryakumar Yadav b Hardik Pandya,21,17,1,1,123.53,david miller,RSA,P123
848,INDIA vs SOUTH AFRICA,South Africa,7,Marco Jansen,b Bumrah,2,4,0,0,50.00,marco jansen,RSA,P124
849,INDIA vs SOUTH AFRICA,South Africa,8,Keshav Maharaj,not out,2,7,0,0,28.57,keshav maharaj,RSA,P132
850,INDIA vs SOUTH AFRICA,South Africa,9,Kagiso Rabada,c Suryakumar Yadav b Hardik Pandya,4,3,1,0,133.33,kagiso rabada,RSA,P134
851,INDIA vs SOUTH AFRICA,South Africa,10,Anrich Nortje,not out,1,1,0,0,100.00,anrich nortje,RSA,P133

In [41]:
dfb.to_csv("batting_summary_clean.csv", index=False)

In [42]:
dfb["player_id"].isna().sum()

11

In [43]:
data2=pd.read_csv('bowling_summary.csv')
dfbo=pd.DataFrame(data2)
dfbo

,match,teamInnings,bowlerName,overs,maidens,runs,wickets,noBalls,wides,economy
0,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Ali Khan,4.0,0,41,1,0,2,10.2
1,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Netravalkar,2.0,0,16,0,0,0,8.0
2,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Harmeet Singh,4.0,0,27,1,0,0,6.8
3,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Jessy Singh,3.0,0,24,0,0,0,8.0
4,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,van Schalkwyk,3.0,0,34,0,0,0,11.3
...,...,...,...,...,...,...,...,...,...,...
590,INDIA vs SOUTH AFRICA,INDIA,Jasprit Bumrah,4.0,0,18,2,0,0,4.5
591,INDIA vs SOUTH AFRICA,INDIA,Axar Patel,4.0,0,49,1,0,2,12.2
592,INDIA vs SOUTH AFRICA,INDIA,Kuldeep Yadav,4.0,0,45,0,0,0,11.2
593,INDIA vs SOUTH AFRICA,INDIA,Hardik Pandya,3.0,0,20,3,1,1,6.7
594,INDIA vs SOUTH AFRICA,INDIA,Ravindra Jadeja,1.0,0,12,0,0,0,12.0

In [44]:
dfbo = dfbo.rename(columns={
    "match": "match_name",
    "teamInnings": "team",
    "bowlerName": "player_name",
    "noBalls": "no_balls"
})
dfbo

,match_name,team,player_name,overs,maidens,runs,wickets,no_balls,wides,economy
0,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Ali Khan,4.0,0,41,1,0,2,10.2
1,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Netravalkar,2.0,0,16,0,0,0,8.0
2,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Harmeet Singh,4.0,0,27,1,0,0,6.8
3,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Jessy Singh,3.0,0,24,0,0,0,8.0
4,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,van Schalkwyk,3.0,0,34,0,0,0,11.3
...,...,...,...,...,...,...,...,...,...,...
590,INDIA vs SOUTH AFRICA,INDIA,Jasprit Bumrah,4.0,0,18,2,0,0,4.5
591,INDIA vs SOUTH AFRICA,INDIA,Axar Patel,4.0,0,49,1,0,2,12.2
592,INDIA vs SOUTH AFRICA,INDIA,Kuldeep Yadav,4.0,0,45,0,0,0,11.2
593,INDIA vs SOUTH AFRICA,INDIA,Hardik Pandya,3.0,0,20,3,1,1,6.7
594,INDIA vs SOUTH AFRICA,INDIA,Ravindra Jadeja,1.0,0,12,0,0,0,12.0

In [53]:
dfbo["player_name_clean"] = (
    dfbo["player_name"]
    .str.lower()
    .str.replace(r"\(c\s*&\s*wk\)|\(wk\)|\(c\)", "", regex=True)
    .str.replace(r"\s*wk-\s*$", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [54]:
dfbo["player_name_clean"] = dfbo.apply(
    lambda r: resolve_name(r, df),
    axis=1
)

In [47]:
team_map = {
    "india": "IND",
    "england": "ENG",
    "ireland": "IRE",
    "canada": "CAN",
    "united states": "USA",
    "united state": "USA",
    "united states of america": "USA",
    "usa": "USA",
    "australia": "AUS",
    "scotland": "SCO",
    "oman": "OMN",
    "south africa": "RSA",
    "sri lanka": "SL",
    "new zealand": "NZ",
    "afghanistan": "AFG",
    "nepal": "NEP",
    "west indies": "WI",
    "uganda": "UGA",
    "papua new guinea": "PNG",
    "namibia": "NAM",
    "netherlands": "NED",
    "bangladesh": "BAN",
    "pakistan": "PAK"
}


dfbo["team_clean"] = (
    dfbo["team"]
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .map(team_map)   # reuse the SAME team_map you already created
)
dfbo

,match_name,team,player_name,overs,maidens,runs,wickets,no_balls,wides,economy,player_name_clean,team_clean
0,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Ali Khan,4.0,0,41,1,0,2,10.2,ali khan,USA
1,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Netravalkar,2.0,0,16,0,0,0,8.0,netravalkar,USA
2,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Harmeet Singh,4.0,0,27,1,0,0,6.8,harmeet singh,USA
3,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Jessy Singh,3.0,0,24,0,0,0,8.0,jessy singh,USA
4,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,van Schalkwyk,3.0,0,34,0,0,0,11.3,van schalkwyk,USA
...,...,...,...,...,...,...,...,...,...,...,...,...
590,INDIA vs SOUTH AFRICA,INDIA,Jasprit Bumrah,4.0,0,18,2,0,0,4.5,jasprit bumrah,IND
591,INDIA vs SOUTH AFRICA,INDIA,Axar Patel,4.0,0,49,1,0,2,12.2,axar patel,IND
592,INDIA vs SOUTH AFRICA,INDIA,Kuldeep Yadav,4.0,0,45,0,0,0,11.2,kuldeep yadav,IND
593,INDIA vs SOUTH AFRICA,INDIA,Hardik Pandya,3.0,0,20,3,1,1,6.7,hardik pandya,IND
594,INDIA vs SOUTH AFRICA,INDIA,Ravindra Jadeja,1.0,0,12,0,0,0,12.0,ravindra jadeja,IND

In [55]:
dfbo = dfbo.drop(
    columns=[c for c in dfbo.columns if c.startswith("player_id")],
    errors="ignore"
)

dfbo = dfbo.merge(
    df[["player_id", "player_name_clean", "team_clean"]],
    on=["player_name_clean", "team_clean"],
    how="left"
)
dfbo

,match_name,team,player_name,overs,maidens,runs,wickets,no_balls,wides,economy,player_name_clean,team_clean,player_id
0,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Ali Khan,4.0,0,41,1,0,2,10.2,ali khan,USA,P72
1,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Netravalkar,2.0,0,16,0,0,0,8.0,saurabh netravalkar,USA,P75
2,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Harmeet Singh,4.0,0,27,1,0,0,6.8,harmeet singh,USA,P66
3,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,Jessy Singh,3.0,0,24,0,0,0,8.0,jessy singh,USA,NaN
4,CANADA vs UNITED STATES OF AMERICA,UNITED STATES OF AMERICA,van Schalkwyk,3.0,0,34,0,0,0,11.3,shadley van schalkwyk,USA,P68
...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,INDIA vs SOUTH AFRICA,INDIA,Jasprit Bumrah,4.0,0,18,2,0,0,4.5,jasprit bumrah,IND,P14
591,INDIA vs SOUTH AFRICA,INDIA,Axar Patel,4.0,0,49,1,0,2,12.2,axar patel,IND,P8
592,INDIA vs SOUTH AFRICA,INDIA,Kuldeep Yadav,4.0,0,45,0,0,0,11.2,kuldeep yadav,IND,P11
593,INDIA vs SOUTH AFRICA,INDIA,Hardik Pandya,3.0,0,20,3,1,1,6.7,hardik pandya,IND,P5
594,INDIA vs SOUTH AFRICA,INDIA,Ravindra Jadeja,1.0,0,12,0,0,0,12.0,ravindra jadeja,IND,P7

In [57]:
dfbo["player_id"].isna().sum()

1

In [58]:
dfbo.to_csv('bowling_summary_clean.csv', index=False)