Data Cleaning

In [12]:
import pandas as pd

df=pd.DataFrame(pd.read_csv('t20wc.csv'))
df.head()

,Match_No,Date,Team1,Score_Team1,Team2,Score_Team2,Margin/Result,Ground,Link
0,1,"SAT, JUN 1 2024",CANADA,194-5 (20),UNITED STATES OF AMERICA,197-3 (17.4),United States won by 7 wkts,"1st Match, Group A • Dallas, Grand Prairie Sta...",https://www.cricbuzz.com/live-cricket-scores/8...
1,2,"SAT, JUN 1 2024",PAPUA NEW GUINEA,136-8 (20),WEST INDIES,137-5 (19),West Indies won by 5 wkts,"2nd Match, Group C • Guyana, Providence Stadium",https://www.cricbuzz.com/live-cricket-scores/8...
2,3,"SUN, JUN 2 2024",OMAN,109 (19.4),NAMIBIA,109-6 (20),Match tied (Namibia won the super over),"3rd Match, Group B • Bridgetown, Barbados, Ken...",https://www.cricbuzz.com/live-cricket-scores/8...
3,4,"SUN, JUN 2 2024",SRI LANKA,77 (19.1),SOUTH AFRICA,80-4 (16.2),South Africa won by 6 wkts,"4th Match, Group D • New York, Nassau County I...",https://www.cricbuzz.com/live-cricket-scores/8...
4,5,"MON, JUN 3 2024",AFGHANISTAN,183-5 (20),UGANDA,58 (16),Afghanistan won by 125 runs,"5th Match, Group C • Guyana, Providence Stadium",https://www.cricbuzz.com/live-cricket-scores/8...

In [11]:
# df.index=df['Match_No']
# del df['Match_No']
df.head()

,Date,Team1,Score_Team1,Team2,Score_Team2,Margin/Result,Ground,Link
Match_No,,,,,,,,
1,"SAT, JUN 1 2024",CANADA,194-5 (20),UNITED STATES OF AMERICA,197-3 (17.4),United States won by 7 wkts,"1st Match, Group A • Dallas, Grand Prairie Sta...",https://www.cricbuzz.com/live-cricket-scores/8...
2,"SAT, JUN 1 2024",PAPUA NEW GUINEA,136-8 (20),WEST INDIES,137-5 (19),West Indies won by 5 wkts,"2nd Match, Group C • Guyana, Providence Stadium",https://www.cricbuzz.com/live-cricket-scores/8...
3,"SUN, JUN 2 2024",OMAN,109 (19.4),NAMIBIA,109-6 (20),Match tied (Namibia won the super over),"3rd Match, Group B • Bridgetown, Barbados, Ken...",https://www.cricbuzz.com/live-cricket-scores/8...
4,"SUN, JUN 2 2024",SRI LANKA,77 (19.1),SOUTH AFRICA,80-4 (16.2),South Africa won by 6 wkts,"4th Match, Group D • New York, Nassau County I...",https://www.cricbuzz.com/live-cricket-scores/8...
5,"MON, JUN 3 2024",AFGHANISTAN,183-5 (20),UGANDA,58 (16),Afghanistan won by 125 runs,"5th Match, Group C • Guyana, Providence Stadium",https://www.cricbuzz.com/live-cricket-scores/8...

In [13]:
import re
df['Score_Team1'] = df['Score_Team1'].astype(str).str.replace(
    r'\s*\(.*?\)', '', regex=True
)

df['Score_Team2'] = df['Score_Team2'].astype(str).str.replace(
    r'\s*\(.*?\)', '', regex=True
)
df['Ground'] = df['Ground'].astype(str).str.replace(
    r'^.*,\s*', '', regex=True
)
df

,Match_No,Date,Team1,Score_Team1,Team2,Score_Team2,Margin/Result,Ground,Link
0,1,"SAT, JUN 1 2024",CANADA,194-5,UNITED STATES OF AMERICA,197-3,United States won by 7 wkts,Grand Prairie Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
1,2,"SAT, JUN 1 2024",PAPUA NEW GUINEA,136-8,WEST INDIES,137-5,West Indies won by 5 wkts,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
2,3,"SUN, JUN 2 2024",OMAN,109,NAMIBIA,109-6,Match tied (Namibia won the super over),Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...
3,4,"SUN, JUN 2 2024",SRI LANKA,77,SOUTH AFRICA,80-4,South Africa won by 6 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
4,5,"MON, JUN 3 2024",AFGHANISTAN,183-5,UGANDA,58,Afghanistan won by 125 runs,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
5,6,"MON, JUN 3 2024",SCOTLAND,90-0,ENGLAND,nan,No result,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...
6,7,"MON, JUN 3 2024",NEPAL,106,NETHERLANDS,109-4,Netherlands won by 6 wkts,Grand Prairie Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
7,8,"WED, JUN 5 2024",IRELAND,96,INDIA,97-2,India won by 8 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
8,9,"WED, JUN 5 2024",PAPUA NEW GUINEA,77,UGANDA,78-7,Uganda won by 3 wkts,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
9,10,"WED, JUN 5 2024",AUSTRALIA,164-5,OMAN,125-9,Australia won by 39 runs,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...
10,11,"WED, JUN 5 2024",PAKISTAN,159-7,UNITED STATES OF AMERICA,159-3,Match tied (United States won the super over),Grand Prairie Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
11,12,"THU, JUN 6 2024",NAMIBIA,155-9,SCOTLAND,157-5,Scotland won by 5 wkts,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...
12,13,"THU, JUN 6 2024",CANADA,137-7,IRELAND,125-7,Canada won by 12 runs,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
13,14,"FRI, JUN 7 2024",AFGHANISTAN,159-6,NEW ZEALAND,75,Afghanistan won by 84 runs,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
14,15,"FRI, JUN 7 2024",SRI LANKA,124-9,BANGLADESH,125-8,Bangladesh won by 2 wkts,Grand Prairie Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
15,16,"FRI, JUN 7 2024",NETHERLANDS,103-9,SOUTH AFRICA,106-6,South Africa won by 4 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
16,17,"FRI, JUN 7 2024",AUSTRALIA,201-7,ENGLAND,165-6,Australia won by 36 runs,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...
17,18,"SAT, JUN 8 2024",WEST INDIES,173-5,UGANDA,39,West Indies won by 134 runs,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
18,19,"SAT, JUN 8 2024",INDIA,119,PAKISTAN,113-7,India won by 6 runs,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
19,20,"SAT, JUN 8 2024",OMAN,150-7,SCOTLAND,153-3,Scotland won by 7 wkts,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
20,21,"MON, JUN 10 2024",SOUTH AFRICA,113-6,BANGLADESH,109-7,South Africa won by 4 runs,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
21,22,"TUE, JUN 11 2024",CANADA,106-7,PAKISTAN,107-3,Pakistan won by 7 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
22,23,"TUE, JUN 11 2024",SRI LANKA,nan,NEPAL,nan,Match abandoned due to rain,Central Broward Regional Park Stadium Turf Ground,https://www.cricbuzz.com/live-cricket-scores/8...
23,24,"TUE, JUN 11 2024",NAMIBIA,72,AUSTRALIA,74-1,Australia won by 9 wkts,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
24,25,"TUE, JUN 11 2024",UNITED STATES OF AMERICA,110-8,INDIA,111-3,India won by 7 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
25,26,"WED, JUN 12 2024",WEST INDIES,149-9,NEW ZEALAND,136-9,West Indies won by 13 runs,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
26,27,"WED, JUN 12 2024",BANGLADESH,159-5,NETHERLANDS,134-8,Bangladesh won by 25 runs,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...
27,28,"THU, JUN 13 2024",OMAN,47,ENGLAND,50-2,England won by 8 wkts,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
28,29,"THU, JUN 13 2024",PAPUA NEW GUINEA,95,AFGHANISTAN,101-3,Afghanistan won by 7 wkts,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
29,30,"THU, JUN 13 2024",UNITED STATES OF AMERICA,nan,IRELAND,nan,Match abandoned due to rain,Central Broward Regional Park Stadium Turf Ground,https://www.cricbuzz.com/live-cricket-scores/8...
30,31,"FRI, JUN 14 2024",SOUTH AFRICA,115-7,NEPAL,114-7,South Africa won by 1 run,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...
31,32,"FRI, JUN 14 2024",UGANDA,40,NEW ZEALAND,41-1,New Zealand won by 9 wkts,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
32,33,"FRI, JUN 14 2024",INDIA,nan,CANADA,nan,Match abandoned due to wet outfield (no toss),Central Broward Regional Park Stadium Turf Ground,https://www.cricbuzz.com/live-cricket-scores/8...
33,34,"FRI, JUN 14 2024",ENGLAND,122-5,NAMIBIA,84-3,England won by 41 runs (DLS method),Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
34,35,"SAT, JUN 15 2024",SCOTLAND,180-5,AUSTRALIA,186-5,Australia won by 5 wkts,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
35,36,"SAT, JUN 15 2024",IRELAND,106-9,PAKISTAN,111-7,Pakistan won by 3 wkts,Central Broward Regional Park Stadium Turf Ground,https://www.cricbuzz.com/live-cricket-scores/8...
36,37,"SUN, JUN 16 2024",BANGLADESH,106,NEPAL,85,Bangladesh won by 21 runs,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...
37,38,"SUN, JUN 16 2024",SRI LANKA,201-6,NETHERLANDS,118,Sri Lanka won by 83 runs,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
38,39,"SUN, JUN 16 2024",PAPUA NEW GUINEA,78,NEW ZEALAND,79-3,New Zealand won by 7 wkts,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
39,40,"MON, JUN 17 2024",WEST INDIES,218-5,AFGHANISTAN,114,West Indies won by 104 runs,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
40,41,"WED, JUN 19 2024",SOUTH AFRICA,194-4,UNITED STATES OF AMERICA,176-6,South Africa won by 18 runs,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
41,42,"WED, JUN 19 2024",WEST INDIES,180-4,ENGLAND,181-2,England won by 8 wkts,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
42,43,"WED, JUN 19 2024",INDIA,181-8,AFGHANISTAN,134,India won by 47 runs,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...
43,44,"THU, JUN 20 2024",BANGLADESH,140-8,AUSTRALIA,100-2,Australia won by 28 runs (DLS Method),Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
44,45,"THU, JUN 20 2024",SOUTH AFRICA,163-6,ENGLAND,156-6,South Africa won by 7 runs,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
45,46,"FRI, JUN 21 2024",UNITED STATES OF AMERICA,128,WEST INDIES,130-1,West Indies won by 9 wkts,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...
46,47,"FRI, JUN 21 2024",INDIA,196-5,BANGLADESH,146-8,India won by 50 runs,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
47,48,"SAT, JUN 22 2024",AFGHANISTAN,148-6,AUSTRALIA,127,Afghanistan won by 21 runs,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...
48,49,"SAT, JUN 22 2024",UNITED STATES OF AMERICA,115,ENGLAND,117-0,England won by 10 wkts,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...
49,50,"SUN, JUN 23 2024",WEST INDIES,135-8,SOUTH AFRICA,124-7,South Africa won by 3 wkts - 2nd inns reduced ...,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
50,51,"SUN, JUN 23 2024",INDIA,205-5,AUSTRALIA,181-7,India won by 24 runs,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
51,52,"MON, JUN 24 2024",AFGHANISTAN,115-5,BANGLADESH,105,Afghanistan won by 8 runs (Match reduced to 19...,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...
52,53,"WED, JUN 26 2024",AFGHANISTAN,56,SOUTH AFRICA,60-1,South Africa won by 9 wkts,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
53,54,"WED, JUN 26 2024",INDIA,171-7,ENGLAND,103,India won by 68 runs,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...
54,55,"SAT, JUN 29 2024",INDIA,176-7,SOUTH AFRICA,169-8,India won by 7 runs,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...

In [15]:
df.groupby('Ground')['Match_No'].count()

Ground
Arnos Vale Ground                                    5
Brian Lara Stadium                                   5
Central Broward Regional Park Stadium Turf Ground    4
Daren Sammy National Cricket Stadium                 6
Grand Prairie Stadium                                4
Kensington Oval                                      9
Nassau County International Cricket Stadium          8
Providence Stadium                                   6
Sir Vivian Richards Stadium                          8
Name: Match_No, dtype: int64

In [19]:
df['First_Innings_Runs'] = (
    df['Score_Team1']
    .astype(str)
    .str.extract(r'^(\d+)')   # extract runs before '-'
    .astype(float)
)
df['Second_Innings_Runs'] = (
    df['Score_Team2']
    .astype(str)
    .str.extract(r'^(\d+)')   # extract runs before '-'
    .astype(float)
)
df

,Match_No,Date,Team1,Score_Team1,Team2,Score_Team2,Margin/Result,Ground,Link,First_Innings_Runs,Second_Innings_Runs
0,1,"SAT, JUN 1 2024",CANADA,194-5,UNITED STATES OF AMERICA,197-3,United States won by 7 wkts,Grand Prairie Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,194.0,197.0
1,2,"SAT, JUN 1 2024",PAPUA NEW GUINEA,136-8,WEST INDIES,137-5,West Indies won by 5 wkts,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,136.0,137.0
2,3,"SUN, JUN 2 2024",OMAN,109,NAMIBIA,109-6,Match tied (Namibia won the super over),Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,109.0,109.0
3,4,"SUN, JUN 2 2024",SRI LANKA,77,SOUTH AFRICA,80-4,South Africa won by 6 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,77.0,80.0
4,5,"MON, JUN 3 2024",AFGHANISTAN,183-5,UGANDA,58,Afghanistan won by 125 runs,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,183.0,58.0
5,6,"MON, JUN 3 2024",SCOTLAND,90-0,ENGLAND,nan,No result,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,90.0,NaN
6,7,"MON, JUN 3 2024",NEPAL,106,NETHERLANDS,109-4,Netherlands won by 6 wkts,Grand Prairie Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,106.0,109.0
7,8,"WED, JUN 5 2024",IRELAND,96,INDIA,97-2,India won by 8 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,96.0,97.0
8,9,"WED, JUN 5 2024",PAPUA NEW GUINEA,77,UGANDA,78-7,Uganda won by 3 wkts,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,77.0,78.0
9,10,"WED, JUN 5 2024",AUSTRALIA,164-5,OMAN,125-9,Australia won by 39 runs,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,164.0,125.0
10,11,"WED, JUN 5 2024",PAKISTAN,159-7,UNITED STATES OF AMERICA,159-3,Match tied (United States won the super over),Grand Prairie Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,159.0,159.0
11,12,"THU, JUN 6 2024",NAMIBIA,155-9,SCOTLAND,157-5,Scotland won by 5 wkts,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,155.0,157.0
12,13,"THU, JUN 6 2024",CANADA,137-7,IRELAND,125-7,Canada won by 12 runs,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,137.0,125.0
13,14,"FRI, JUN 7 2024",AFGHANISTAN,159-6,NEW ZEALAND,75,Afghanistan won by 84 runs,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,159.0,75.0
14,15,"FRI, JUN 7 2024",SRI LANKA,124-9,BANGLADESH,125-8,Bangladesh won by 2 wkts,Grand Prairie Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,124.0,125.0
15,16,"FRI, JUN 7 2024",NETHERLANDS,103-9,SOUTH AFRICA,106-6,South Africa won by 4 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,103.0,106.0
16,17,"FRI, JUN 7 2024",AUSTRALIA,201-7,ENGLAND,165-6,Australia won by 36 runs,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,201.0,165.0
17,18,"SAT, JUN 8 2024",WEST INDIES,173-5,UGANDA,39,West Indies won by 134 runs,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,173.0,39.0
18,19,"SAT, JUN 8 2024",INDIA,119,PAKISTAN,113-7,India won by 6 runs,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,119.0,113.0
19,20,"SAT, JUN 8 2024",OMAN,150-7,SCOTLAND,153-3,Scotland won by 7 wkts,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,150.0,153.0
20,21,"MON, JUN 10 2024",SOUTH AFRICA,113-6,BANGLADESH,109-7,South Africa won by 4 runs,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,113.0,109.0
21,22,"TUE, JUN 11 2024",CANADA,106-7,PAKISTAN,107-3,Pakistan won by 7 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,106.0,107.0
22,23,"TUE, JUN 11 2024",SRI LANKA,nan,NEPAL,nan,Match abandoned due to rain,Central Broward Regional Park Stadium Turf Ground,https://www.cricbuzz.com/live-cricket-scores/8...,NaN,NaN
23,24,"TUE, JUN 11 2024",NAMIBIA,72,AUSTRALIA,74-1,Australia won by 9 wkts,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,72.0,74.0
24,25,"TUE, JUN 11 2024",UNITED STATES OF AMERICA,110-8,INDIA,111-3,India won by 7 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,110.0,111.0
25,26,"WED, JUN 12 2024",WEST INDIES,149-9,NEW ZEALAND,136-9,West Indies won by 13 runs,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,149.0,136.0
26,27,"WED, JUN 12 2024",BANGLADESH,159-5,NETHERLANDS,134-8,Bangladesh won by 25 runs,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...,159.0,134.0
27,28,"THU, JUN 13 2024",OMAN,47,ENGLAND,50-2,England won by 8 wkts,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,47.0,50.0
28,29,"THU, JUN 13 2024",PAPUA NEW GUINEA,95,AFGHANISTAN,101-3,Afghanistan won by 7 wkts,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,95.0,101.0
29,30,"THU, JUN 13 2024",UNITED STATES OF AMERICA,nan,IRELAND,nan,Match abandoned due to rain,Central Broward Regional Park Stadium Turf Ground,https://www.cricbuzz.com/live-cricket-scores/8...,NaN,NaN
30,31,"FRI, JUN 14 2024",SOUTH AFRICA,115-7,NEPAL,114-7,South Africa won by 1 run,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...,115.0,114.0
31,32,"FRI, JUN 14 2024",UGANDA,40,NEW ZEALAND,41-1,New Zealand won by 9 wkts,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,40.0,41.0
32,33,"FRI, JUN 14 2024",INDIA,nan,CANADA,nan,Match abandoned due to wet outfield (no toss),Central Broward Regional Park Stadium Turf Ground,https://www.cricbuzz.com/live-cricket-scores/8...,NaN,NaN
33,34,"FRI, JUN 14 2024",ENGLAND,122-5,NAMIBIA,84-3,England won by 41 runs (DLS method),Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,122.0,84.0
34,35,"SAT, JUN 15 2024",SCOTLAND,180-5,AUSTRALIA,186-5,Australia won by 5 wkts,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,180.0,186.0
35,36,"SAT, JUN 15 2024",IRELAND,106-9,PAKISTAN,111-7,Pakistan won by 3 wkts,Central Broward Regional Park Stadium Turf Ground,https://www.cricbuzz.com/live-cricket-scores/8...,106.0,111.0
36,37,"SUN, JUN 16 2024",BANGLADESH,106,NEPAL,85,Bangladesh won by 21 runs,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...,106.0,85.0
37,38,"SUN, JUN 16 2024",SRI LANKA,201-6,NETHERLANDS,118,Sri Lanka won by 83 runs,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,201.0,118.0
38,39,"SUN, JUN 16 2024",PAPUA NEW GUINEA,78,NEW ZEALAND,79-3,New Zealand won by 7 wkts,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,78.0,79.0
39,40,"MON, JUN 17 2024",WEST INDIES,218-5,AFGHANISTAN,114,West Indies won by 104 runs,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,218.0,114.0
40,41,"WED, JUN 19 2024",SOUTH AFRICA,194-4,UNITED STATES OF AMERICA,176-6,South Africa won by 18 runs,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,194.0,176.0
41,42,"WED, JUN 19 2024",WEST INDIES,180-4,ENGLAND,181-2,England won by 8 wkts,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,180.0,181.0
42,43,"WED, JUN 19 2024",INDIA,181-8,AFGHANISTAN,134,India won by 47 runs,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,181.0,134.0
43,44,"THU, JUN 20 2024",BANGLADESH,140-8,AUSTRALIA,100-2,Australia won by 28 runs (DLS Method),Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,140.0,100.0
44,45,"THU, JUN 20 2024",SOUTH AFRICA,163-6,ENGLAND,156-6,South Africa won by 7 runs,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,163.0,156.0
45,46,"FRI, JUN 21 2024",UNITED STATES OF AMERICA,128,WEST INDIES,130-1,West Indies won by 9 wkts,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,128.0,130.0
46,47,"FRI, JUN 21 2024",INDIA,196-5,BANGLADESH,146-8,India won by 50 runs,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,196.0,146.0
47,48,"SAT, JUN 22 2024",AFGHANISTAN,148-6,AUSTRALIA,127,Afghanistan won by 21 runs,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...,148.0,127.0
48,49,"SAT, JUN 22 2024",UNITED STATES OF AMERICA,115,ENGLAND,117-0,England won by 10 wkts,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,115.0,117.0
49,50,"SUN, JUN 23 2024",WEST INDIES,135-8,SOUTH AFRICA,124-7,South Africa won by 3 wkts - 2nd inns reduced ...,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,135.0,124.0
50,51,"SUN, JUN 23 2024",INDIA,205-5,AUSTRALIA,181-7,India won by 24 runs,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,205.0,181.0
51,52,"MON, JUN 24 2024",AFGHANISTAN,115-5,BANGLADESH,105,Afghanistan won by 8 runs (Match reduced to 19...,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...,115.0,105.0
52,53,"WED, JUN 26 2024",AFGHANISTAN,56,SOUTH AFRICA,60-1,South Africa won by 9 wkts,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,56.0,60.0
53,54,"WED, JUN 26 2024",INDIA,171-7,ENGLAND,103,India won by 68 runs,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,171.0,103.0
54,55,"SAT, JUN 29 2024",INDIA,176-7,SOUTH AFRICA,169-8,India won by 7 runs,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,176.0,169.0

In [22]:
df.groupby('Ground')['First_Innings_Runs'].mean().round(0)

Ground
Arnos Vale Ground                                    129.0
Brian Lara Stadium                                    84.0
Central Broward Regional Park Stadium Turf Ground    106.0
Daren Sammy National Cricket Stadium                 191.0
Grand Prairie Stadium                                146.0
Kensington Oval                                      147.0
Nassau County International Cricket Stadium          108.0
Providence Stadium                                   150.0
Sir Vivian Richards Stadium                          132.0
Name: First_Innings_Runs, dtype: float64

In [26]:
df['Batting_First_Won'] = (
    df['First_Innings_Runs'] > df['Second_Innings_Runs']
)

df['Chasing_Won'] = ~df['Batting_First_Won']
df

,Match_No,Date,Team1,Score_Team1,Team2,Score_Team2,Margin/Result,Ground,Link,First_Innings_Runs,Second_Innings_Runs,Batting_First_Won,Chasing_Won
0,1,"SAT, JUN 1 2024",CANADA,194-5,UNITED STATES OF AMERICA,197-3,United States won by 7 wkts,Grand Prairie Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,194.0,197.0,False,True
1,2,"SAT, JUN 1 2024",PAPUA NEW GUINEA,136-8,WEST INDIES,137-5,West Indies won by 5 wkts,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,136.0,137.0,False,True
2,3,"SUN, JUN 2 2024",OMAN,109,NAMIBIA,109-6,Match tied (Namibia won the super over),Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,109.0,109.0,False,True
3,4,"SUN, JUN 2 2024",SRI LANKA,77,SOUTH AFRICA,80-4,South Africa won by 6 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,77.0,80.0,False,True
4,5,"MON, JUN 3 2024",AFGHANISTAN,183-5,UGANDA,58,Afghanistan won by 125 runs,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,183.0,58.0,True,False
5,6,"MON, JUN 3 2024",SCOTLAND,90-0,ENGLAND,nan,No result,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,90.0,NaN,False,True
6,7,"MON, JUN 3 2024",NEPAL,106,NETHERLANDS,109-4,Netherlands won by 6 wkts,Grand Prairie Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,106.0,109.0,False,True
7,8,"WED, JUN 5 2024",IRELAND,96,INDIA,97-2,India won by 8 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,96.0,97.0,False,True
8,9,"WED, JUN 5 2024",PAPUA NEW GUINEA,77,UGANDA,78-7,Uganda won by 3 wkts,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,77.0,78.0,False,True
9,10,"WED, JUN 5 2024",AUSTRALIA,164-5,OMAN,125-9,Australia won by 39 runs,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,164.0,125.0,True,False
10,11,"WED, JUN 5 2024",PAKISTAN,159-7,UNITED STATES OF AMERICA,159-3,Match tied (United States won the super over),Grand Prairie Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,159.0,159.0,False,True
11,12,"THU, JUN 6 2024",NAMIBIA,155-9,SCOTLAND,157-5,Scotland won by 5 wkts,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,155.0,157.0,False,True
12,13,"THU, JUN 6 2024",CANADA,137-7,IRELAND,125-7,Canada won by 12 runs,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,137.0,125.0,True,False
13,14,"FRI, JUN 7 2024",AFGHANISTAN,159-6,NEW ZEALAND,75,Afghanistan won by 84 runs,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,159.0,75.0,True,False
14,15,"FRI, JUN 7 2024",SRI LANKA,124-9,BANGLADESH,125-8,Bangladesh won by 2 wkts,Grand Prairie Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,124.0,125.0,False,True
15,16,"FRI, JUN 7 2024",NETHERLANDS,103-9,SOUTH AFRICA,106-6,South Africa won by 4 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,103.0,106.0,False,True
16,17,"FRI, JUN 7 2024",AUSTRALIA,201-7,ENGLAND,165-6,Australia won by 36 runs,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,201.0,165.0,True,False
17,18,"SAT, JUN 8 2024",WEST INDIES,173-5,UGANDA,39,West Indies won by 134 runs,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,173.0,39.0,True,False
18,19,"SAT, JUN 8 2024",INDIA,119,PAKISTAN,113-7,India won by 6 runs,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,119.0,113.0,True,False
19,20,"SAT, JUN 8 2024",OMAN,150-7,SCOTLAND,153-3,Scotland won by 7 wkts,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,150.0,153.0,False,True
20,21,"MON, JUN 10 2024",SOUTH AFRICA,113-6,BANGLADESH,109-7,South Africa won by 4 runs,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,113.0,109.0,True,False
21,22,"TUE, JUN 11 2024",CANADA,106-7,PAKISTAN,107-3,Pakistan won by 7 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,106.0,107.0,False,True
22,23,"TUE, JUN 11 2024",SRI LANKA,nan,NEPAL,nan,Match abandoned due to rain,Central Broward Regional Park Stadium Turf Ground,https://www.cricbuzz.com/live-cricket-scores/8...,NaN,NaN,False,True
23,24,"TUE, JUN 11 2024",NAMIBIA,72,AUSTRALIA,74-1,Australia won by 9 wkts,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,72.0,74.0,False,True
24,25,"TUE, JUN 11 2024",UNITED STATES OF AMERICA,110-8,INDIA,111-3,India won by 7 wkts,Nassau County International Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,110.0,111.0,False,True
25,26,"WED, JUN 12 2024",WEST INDIES,149-9,NEW ZEALAND,136-9,West Indies won by 13 runs,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,149.0,136.0,True,False
26,27,"WED, JUN 12 2024",BANGLADESH,159-5,NETHERLANDS,134-8,Bangladesh won by 25 runs,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...,159.0,134.0,True,False
27,28,"THU, JUN 13 2024",OMAN,47,ENGLAND,50-2,England won by 8 wkts,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,47.0,50.0,False,True
28,29,"THU, JUN 13 2024",PAPUA NEW GUINEA,95,AFGHANISTAN,101-3,Afghanistan won by 7 wkts,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,95.0,101.0,False,True
29,30,"THU, JUN 13 2024",UNITED STATES OF AMERICA,nan,IRELAND,nan,Match abandoned due to rain,Central Broward Regional Park Stadium Turf Ground,https://www.cricbuzz.com/live-cricket-scores/8...,NaN,NaN,False,True
30,31,"FRI, JUN 14 2024",SOUTH AFRICA,115-7,NEPAL,114-7,South Africa won by 1 run,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...,115.0,114.0,True,False
31,32,"FRI, JUN 14 2024",UGANDA,40,NEW ZEALAND,41-1,New Zealand won by 9 wkts,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,40.0,41.0,False,True
32,33,"FRI, JUN 14 2024",INDIA,nan,CANADA,nan,Match abandoned due to wet outfield (no toss),Central Broward Regional Park Stadium Turf Ground,https://www.cricbuzz.com/live-cricket-scores/8...,NaN,NaN,False,True
33,34,"FRI, JUN 14 2024",ENGLAND,122-5,NAMIBIA,84-3,England won by 41 runs (DLS method),Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,122.0,84.0,True,False
34,35,"SAT, JUN 15 2024",SCOTLAND,180-5,AUSTRALIA,186-5,Australia won by 5 wkts,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,180.0,186.0,False,True
35,36,"SAT, JUN 15 2024",IRELAND,106-9,PAKISTAN,111-7,Pakistan won by 3 wkts,Central Broward Regional Park Stadium Turf Ground,https://www.cricbuzz.com/live-cricket-scores/8...,106.0,111.0,False,True
36,37,"SUN, JUN 16 2024",BANGLADESH,106,NEPAL,85,Bangladesh won by 21 runs,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...,106.0,85.0,True,False
37,38,"SUN, JUN 16 2024",SRI LANKA,201-6,NETHERLANDS,118,Sri Lanka won by 83 runs,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,201.0,118.0,True,False
38,39,"SUN, JUN 16 2024",PAPUA NEW GUINEA,78,NEW ZEALAND,79-3,New Zealand won by 7 wkts,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,78.0,79.0,False,True
39,40,"MON, JUN 17 2024",WEST INDIES,218-5,AFGHANISTAN,114,West Indies won by 104 runs,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,218.0,114.0,True,False
40,41,"WED, JUN 19 2024",SOUTH AFRICA,194-4,UNITED STATES OF AMERICA,176-6,South Africa won by 18 runs,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,194.0,176.0,True,False
41,42,"WED, JUN 19 2024",WEST INDIES,180-4,ENGLAND,181-2,England won by 8 wkts,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,180.0,181.0,False,True
42,43,"WED, JUN 19 2024",INDIA,181-8,AFGHANISTAN,134,India won by 47 runs,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,181.0,134.0,True,False
43,44,"THU, JUN 20 2024",BANGLADESH,140-8,AUSTRALIA,100-2,Australia won by 28 runs (DLS Method),Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,140.0,100.0,True,False
44,45,"THU, JUN 20 2024",SOUTH AFRICA,163-6,ENGLAND,156-6,South Africa won by 7 runs,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,163.0,156.0,True,False
45,46,"FRI, JUN 21 2024",UNITED STATES OF AMERICA,128,WEST INDIES,130-1,West Indies won by 9 wkts,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,128.0,130.0,False,True
46,47,"FRI, JUN 21 2024",INDIA,196-5,BANGLADESH,146-8,India won by 50 runs,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,196.0,146.0,True,False
47,48,"SAT, JUN 22 2024",AFGHANISTAN,148-6,AUSTRALIA,127,Afghanistan won by 21 runs,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...,148.0,127.0,True,False
48,49,"SAT, JUN 22 2024",UNITED STATES OF AMERICA,115,ENGLAND,117-0,England won by 10 wkts,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,115.0,117.0,False,True
49,50,"SUN, JUN 23 2024",WEST INDIES,135-8,SOUTH AFRICA,124-7,South Africa won by 3 wkts - 2nd inns reduced ...,Sir Vivian Richards Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,135.0,124.0,True,False
50,51,"SUN, JUN 23 2024",INDIA,205-5,AUSTRALIA,181-7,India won by 24 runs,Daren Sammy National Cricket Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,205.0,181.0,True,False
51,52,"MON, JUN 24 2024",AFGHANISTAN,115-5,BANGLADESH,105,Afghanistan won by 8 runs (Match reduced to 19...,Arnos Vale Ground,https://www.cricbuzz.com/live-cricket-scores/8...,115.0,105.0,True,False
52,53,"WED, JUN 26 2024",AFGHANISTAN,56,SOUTH AFRICA,60-1,South Africa won by 9 wkts,Brian Lara Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,56.0,60.0,False,True
53,54,"WED, JUN 26 2024",INDIA,171-7,ENGLAND,103,India won by 68 runs,Providence Stadium,https://www.cricbuzz.com/live-cricket-scores/8...,171.0,103.0,True,False
54,55,"SAT, JUN 29 2024",INDIA,176-7,SOUTH AFRICA,169-8,India won by 7 runs,Kensington Oval,https://www.cricbuzz.com/live-cricket-scores/8...,176.0,169.0,True,False

In [28]:
stadium_analysis = (
    df
    .groupby('Ground', as_index=False)
    .agg(
        Matches=('Match_No', 'count'),
        Avg_First_Innings_Score=('First_Innings_Runs', 'mean'),
        Chasing_Win_Percentage=('Chasing_Won', 'mean')
    )
)

stadium_analysis['Avg_First_Innings_Score'] = stadium_analysis['Avg_First_Innings_Score'].round(1)
stadium_analysis['Chasing_Win_Percentage'] = (stadium_analysis['Chasing_Win_Percentage'] * 100).round(1)

stadium_analysis.sort_values('Matches', ascending=False)

,Ground,Matches,Avg_First_Innings_Score,Chasing_Win_Percentage
5,Kensington Oval,9,146.6,55.6
6,Nassau County International Cricket Stadium,8,107.6,62.5
8,Sir Vivian Richards Stadium,8,132.0,37.5
3,Daren Sammy National Cricket Stadium,6,191.2,33.3
7,Providence Stadium,6,149.8,33.3
0,Arnos Vale Ground,5,128.6,0.0
1,Brian Lara Stadium,5,83.6,80.0
2,Central Broward Regional Park Stadium Turf Ground,4,106.0,100.0
4,Grand Prairie Stadium,4,145.8,100.0

In [29]:
df.to_csv('t20wc_clean.csv')